### PR TITLE
feat: Update Netstats agent

### PR DESCRIPTION
**Pull request by AliakseiMalyshau**
I decided to update a bit Netstats agent for our existing Spark / Fuse nodes on OE and Nethermind. In my opinion existing Dockerfile and run.sh are really complicated solution.

So here I do next changes:

- Updated run.sh by using optargs with long flags, left old flags and added two new - `--network` and `--contact-details`. First one for specifying `WS_SERVER` and `WS_SECRET` for specific network, second one - just FYI who own node
- Updated Dockerfile - existing one had really complex and huge pipeline, was decreased a bit

In addition we avoid to create separate Docker repositories for Spark and Fuse. For this version we could use one repository called: `fusenet/netstat:[some_version]`.

Example usage (with Docker):

```
docker container run \
    --detach \
    --name netstats \
    --network host \
    netstats-agent:latest \
    --network spark \ # Here we use WS parameters related to Spark
    --instance-name "spark-node-1-public" \
    --role "Node" \
    --bridge-version "5.1.0" \
    --netstats-version "2.0.0" \
    --parity-version "2.0.2" \
    --fuseapp-version "1.0.0" \
    --contact-details "cto@fuse.io"
```

I tested it on the new dashboard.

Endpoint: https://netstats.fusespark.io

I ran Spark node with Node role, but just to show the results added all variables in config:

Screenshot from 2022-10-05 14-36-16

### CODE REVIEW

**Comment by AliakseiMalyshau** [comment]
@Andrew-Pohl @leonprou hello team!

Please take a look. Just in case check WS parameters for Spark and Fuse Netstats dashboard (took it from `master` and `testnet` branches).

Thanks!

**Review by Andrew-Pohl — COMMENTED** [review]
LGTM

**Review by leonprou — APPROVED** [review]
Approving,
we describe this as technical debt, right?

**Comment by AliakseiMalyshau** [comment]
Yes, sure, tomorrow I'll explain all Netstats changes, not merging at this moment

**Pull request merged**
